### ISSUE TITLE
[Style] 네비게이션 바 & 모임 더 둘러보기 뷰 구현

### ISSUE THREAD

**Issue by HELLOHIDI** [DOSOPT-CDS-APP-TEAM5/Carrot-iOS#14]
## 🛠 Issue
- 네비게이션 바 & 모임 더 둘러보기 뷰 구현

## 📋 To-do
- [ ] 네비게이션 바 스타일 구현
- [ ] 네비게이션 바 레이아웃 구현
- [ ] 모임 더 둘러보기 컬렉션 뷰 셀 구현
- [ ] 모임 더 둘러보기 컬렉션 푸터 뷰 구현
