### ISSUE TITLE
[Style] 카테고리 & 게시글 컬렉션뷰 구현하기

### ISSUE THREAD

**Issue by HELLOHIDI** [DOSOPT-CDS-APP-TEAM5/Carrot-iOS#18]
## 🛠 Issue
- 카테고리 컬렉션뷰 구현하기

## 📋 To-do
- [ ] 카테고리 더미데이터 생성
- [ ] 카테고리 컬렉션뷰 구현
- [ ] 카테고리 컬렉션뷰 layout 잡기
