### ISSUE TITLE
[Setting] 프로젝트 템플릿 설정

### ISSUE THREAD

**Issue by HELLOHIDI** [DOSOPT-CDS-APP-TEAM5/Carrot-iOS#2]
## 🛠 Issue
- 프로젝트 템플릿 설정

## 📋 To-do
- [ ] 이슈 템플릿 생성
- [ ] PR 템플릿 생성
- [ ] 이슈 태그 추가
- [ ] .gitIgnore 추가
