### ISSUE TITLE
[Style] 모임 가입하기 화면, 상단 배너 구현

### ISSUE THREAD

**Issue by Naknakk** [DOSOPT-CDS-APP-TEAM5/Carrot-iOS#24]
## 🛠 Issue
- 모임 가입하기 화면, 상단 배너 구현

## 📋 To-do
- [x] 최상위 계층의 스크롤 뷰, StackView 생성
- [x] 최상단 ImageView 추가
- [x] 중간의 제목, 썸네일 뷰 추가
- [x] 하단의 모임 태그, 상세 내용 뷰 추가
