### ISSUE TITLE
[Style] 모임 더 둘러보기 화면, 뷰 구현

### ISSUE THREAD

**Issue by timotheekim10** [DOSOPT-CDS-APP-TEAM5/Carrot-iOS#26]
## 🛠 Issue
- 모임 더 둘러보기 화면, 뷰 구현

## 📋 To-do
- [x] 탭맨 뷰컨 구현
- [x] 모임 더 둘러보기 뷰 셀 구현
- [x] 하이라이트 셀 라벨 위치 조정
- [x] SegmentedControl을 이용한 탭바 구현
