### ISSUE TITLE
[Style] 모임 가입하기 화면, 모임 가입하기 버튼 및 하단 테이블 뷰 세팅

### ISSUE THREAD

**Issue by Naknakk** [DOSOPT-CDS-APP-TEAM5/Carrot-iOS#31]
## 🛠 Issue
- 모임 가입하기 화면, 모임 가입하기 버튼 및 하단 테이블 뷰 세팅

## 📋 To-do
- [x] 최하단의 모임 가입하기 버튼 추가. (Floating 느낌으로 언제나 화면에 보이는 것)
- [x] 커스텀 탭바는 일단, StackView로 형태만 만들어 두기
- [x] 하단 테이블 뷰 추가. 각 영역은 섹션으로 구분
- [x] 앨범 섹션, 일단 StackView로 구현
- [x] 일정 섹션, 첫번째 셀, PageViewController로 구현
- [x] 일정 섹션, 두번째 셀, 전체보기 버튼 추가
- [x] 게시판 섹션, 첫번째 셀, 일단 StackView로 구현
- [x] 게시판 섹션, 두번째 셀, 전체보기 버튼 추가
