### ISSUE TITLE
[Feat] 바인딩 및 통신 구현

### ISSUE THREAD

**Issue by timotheekim10** [DOSOPT-CDS-APP-TEAM5/Carrot-iOS#36]
## 🛠 Issue
- 바인딩 및 통신 구현

## 📋 To-do
- [x] 통신 구현
- [x] 더미 데이터 바인딩 구현
- [x] 상세 페이지 이동 구현
- [x] Floating Button 구현
