### ISSUE TITLE
[Feat] 레포지토리 패턴을 이용한 통신 구현

### ISSUE THREAD

**Issue by Naknakk** [DOSOPT-CDS-APP-TEAM5/Carrot-iOS#38]
## 🛠 Issue
- 레포지토리 패턴을 이용한 통신 구현

## 📋 To-do
- [x] 내부 데이터 구조체 만들기
- [x] 통신용 데이터 구조체 만들기
- [x] 레포지토리 패턴을 이용해 통신 구현
