### ISSUE TITLE
[Feat] 모임 프로필 만들기 화면, 회원가입 작성 로직 구현

### ISSUE THREAD

**Issue by Naknakk** [DOSOPT-CDS-APP-TEAM5/Carrot-iOS#41]
## 🛠 Issue
- 모임 프로필 만들기 화면, 회원가입 작성 로직 구현

## 📋 To-do
- [ ] 글자수 동기화 구현
- [ ] 글자수 제한 구현
- [ ] 버튼 활성화 조건 구현
